openapi: 3.0.0
info:
  title: Airline Reservations Management API
  description: |
    API for Airline Management System
  version: 1.0.1
  
servers:
  - url: http://api.example.com/v1
    description: Production Server
    
paths:
  /reservations/{reservation_id}:
    put:
      # @see https://swagger.io/docs/specification/describing-parameters
      summary: Book or re-book a reservation
      description: |
        Example request:
        ```
          PUT http://api.example.com/v1/reservations/d2783fc5-0fee
        ```
      parameters:
        - name: reservation_id
          in: path
          required: true
          description: Unique identifier of the reservation being created or changed
          schema:
            type : string
            example: d2783fc5-0fee

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                outbound:
                  type: object
                  properties:
                    flight_num:
                      type: string
                      example: "AA 253"
                    flight_date:
                      type: string
                      example: "2019-12-31T08:01:00"
                    seats:
                      type: array
                      items:
                        type: string
                returning:
                  type: object
                  properties:
                    flight_num:
                      type: string
                      example: "AA 254"
                    flight_date:
                      type: string
                      example: "2020-01-07T14:16:00"
                    seats:
                      type: array
                      items:
                        type: string
              example: [
              {
                outbound: {
                  flight_num: "AA 253",
                  flight_date: "2019-12-31T08:01:00",
                  seats: [
                    "9C"
                  ]
                },
                returning: {
                  flight_num: "AA 254",
                  flight_date: "2020-01-07T14:16:00",
                  seats: [
                    "10A"
                  ]
                }
              }
            ]

      responses:
        '200': # success response
          description: Successful Reservation
          content:
            application/json:
              schema:
                type: object
                properties:
                  reservation_id:
                    type: string
                    description: some additional description
        '403':
          description: seat(s) unavailable. Booking failed.
          content:
            application/json:
              schema:
                type: string
                description: detailed information    
      